name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ] # enable semantic release on branches for testing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Install deps
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install --pure-lockfile # will run `yarn install` command
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NELSON }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          dry_run: true # for debugging
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.1
            @semantic-release/git@9.0.0
          semantic_version: 17.0.7
